apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tap-gui-catalog-info
  description: A sample catalog for Backstage
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./components/tanzu-app.yaml
    - ./components/spring-petclinic-vets-service.yaml
    - ./groups/default-org.yaml
    - ./systems/tanzu-system.yaml
    - ./domains/tanzu-domain.yaml
