apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tanzu
  description: A sample catalog for Backstage
spec:
  targets:
    - ./components/tanzu-app.yaml
    - ./components/spring-petclinic-vets-service.yaml
    - ./groups/default-org.yaml
    - ./systems/tanzu-system.yaml
    - ./domains/tanzu-domain.yaml
