apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tanzu
  description: Tanzu App catalog for Backstage
spec:
  targets:
    - ./components/tanzu-app.yaml
    - ./groups/default-org.yaml
    - ./systems/tanzu-app-system.yaml
    - ./domains/tanzu-app-domain.yaml
    - ./api/petstore.yaml
    - ./api/tanzu-app.yaml
    - ./ressources/tanzu-app-ressource.yaml
