apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-app
  description: Tanzu App Component
  tags:
    - java
    - spring
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=tanzu-app
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: demo
  system: tanzu-app-system
  owner: default-team
  consumesApis: # list of APIs consumed by the Component
    - petstore-api
  providesApis:
    - tanzu-app-api
  dependsOn: 
    - resource:postgres-tanzu-app
