apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: demo-org
  description: The Demo Organization
  links:
    - url: https://tanzu.vmware.com/support
      title: Tanzu Support Website
spec:
  type: organization
  profile:
    displayName: Default Organization
    email: tanzu@vmware.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [demo-team]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: demo-group
  description: A Demo Group Location
spec:
  targets:
    - ./demo-team.yaml
    - ./fmartin-user.yaml