apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: beenotice
spec:
  profile:
    displayName: Fabien MARTIN
    email: fmartin@vmware.com
    picture: https://avatars.githubusercontent.com/u/96607?v=4
  memberOf: [default-team, demo-team]
